import type { Metadata } from 'next';

import '@/styles/globals.css';

export const metadata: Metadata = {
  title: 'Next.js Starter Package',
  description: 'Generated by @maycomayco',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* emoji favicon */}
      <head>
        <link
          href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>📦</text></svg>"
          rel="icon"
        />
      </head>
      <body className="h-screen w-screen antialiased">
        <div className="flex h-full w-full flex-col">
          <main className="flex-grow overflow-auto bg-[url(/light-bg.svg)] bg-cover bg-repeat">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
